# Generated by Django 5.2.5 on 2025-09-09 09:31

from django.db import migrations

def create_organization(apps, schema_editor):
    Organization = apps.get_model("accounts", "Organization")
    Organization.objects.create(name="Default Organization")

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_organization),
    ]
