# Generated by Django 5.2.5 on 2025-09-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_subscribedemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file_upload",
            field=models.FileField(blank=True, null=True, upload_to="tasks/files"),
        ),
        migrations.AddField(
            model_name="task",
            name="image_upload",
            field=models.ImageField(blank=True, null=True, upload_to="tasks/images/"),
        ),
    ]
