# Generated by Django 5.2.5 on 2025-09-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_create_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"permissions": [("custom_task", "Custom Task Permission")]},
        ),
    ]
