# Generated by Django 5.2.5 on 2025-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="file_upload",
            field=models.FileField(blank=True, null=True, upload_to="tasks/files/"),
        ),
    ]
