# Generated by Django 5.2.5 on 2025-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_task_file_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNASSIGNED", "Unassigned"),
                    ("IN_PROGRESS", "Inprogress"),
                    ("DONE", "Done"),
                    ("ARCHIVED", "Archived"),
                ],
                default="UNASSIGNED",
                max_length=20,
            ),
        ),
    ]
